### ISSUE TITLE
Plz clarify definition of 'crowd' in Performance Evaluation

### ISSUE THREAD

**Issue by RYYAI** [bailvwangzi/repulsion_loss_ssd#6]
First, thanks for your sharing.

Plz clarify the definition of Crowd from "mAP on crowd" in VOC2007 Test. To what degree, the object is defined as " crowd"?

**Comment by bailvwangzi** [comment]
"crowd subset (objects have intra-class IoU greater than 0.1)" described in the paper.
in voc 2007 testset, there are 3421 crowd bbox in 1051 images.
